#!/bin/bash
tree -I '.git|__pycache__|venv|*.egg-info|celerybeat-schedule' --dirsfirst > structure.txt
git add structure.txt
git commit -m "Auto-update structure.txt" --no-verify -q 2>/dev/null
exit 0